### ISSUE TITLE
Fix the logo dissapearing when you change your theme

### ISSUE THREAD

**Issue by maorninja** [BBXD/BBXD#10]
I have no Idea what's causing this.

**Comment by AileenLumina** [comment]
Should be lib/onlineusers.php, line 36. :)

**Comment by JeDa** [comment]
This is added to 3DS Hacks by what I've seen, but... there is a problem.

When it is refreshed by AJAX, the link vanishes. It should be a problem in ajaxcallbacks.php I think...

**Comment by maorninja** [comment]
I fixed it,

**Comment by Super-toad65** [comment]
hmm... seems everything is ok on 3DShacks, only while in preview mode is broken...

**Comment by Super-toad65** [comment]
uhhhh ok

**Comment by maorninja** [comment]
I've figured out why this happens.

Normally, on the board, the logo link is /img/logo.png

However, when changing theme previews, it changes to img/logo.png, while ignoring the board root function. I'll make a quick edit to fix this.
