### ISSUE TITLE
Errors need to be fixed.

### ISSUE THREAD

**Issue by JeDa** [BBXD/BBXD#11]
I did made output all errors (as I had a problem that I couldn't access the profile when edited the code of it), and well, accessing the Plugin manager... I saw a lot of unrelated errors appearing at my face.

[![Blargboard XD Errors](https://files.jedayoshi.me/bbxderrors.png)](https://files.jedayoshi.me/bbxderrors.png)

The code needs to be reviewed for errors... I might look at it when I have time but also @maorninja can if he wants to either.

**Comment by JeDa** [comment]
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined index: forcelayout in /var/www/baia/index.php on line 125
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Warning: Illegal string offset 'primarygroup' in /var/www/baia/lib/links.php on line 178
> 
> Warning: Illegal string offset 'sex' in /var/www/baia/lib/links.php on line 179
> 
> Warning: Illegal string offset 'displayname' in /var/www/baia/lib/links.php on line 180
> 
> Warning: Illegal string offset 'displayname' in /var/www/baia/lib/links.php on line 180
> 
> Warning: Illegal string offset 'minipic' in /var/www/baia/lib/links.php on line 101
> 
> Warning: Illegal string offset 'minipic' in /var/www/baia/lib/links.php on line 102
> 
> Warning: Illegal string offset 'color' in /var/www/baia/plugins/CustomUserNameColors/userLink.php on line 3
> 
> Warning: Illegal string offset 'color' in /var/www/baia/plugins/CustomUserNameColors/userLink.php on line 4
> 
> Warning: Illegal string offset 'name' in /var/www/baia/lib/links.php on line 221
> 
> Warning: Illegal string offset 'id' in /var/www/baia/lib/links.php on line 221
> 
> Warning: Illegal string offset 'id' in /var/www/baia/lib/links.php on line 222
> 
> Warning: Illegal string offset 'id' in /var/www/baia/lib/links.php on line 223
> 
> Warning: Illegal string offset 'name' in /var/www/baia/lib/links.php on line 223
> 
> Notice: Undefined variable: mobileLayout in /var/www/baia/lib/links.php on line 27
> 
> Notice: Undefined variable: loguser in /var/www/baia/plugins/coolshades/postMangler.php on line 3

**Comment by maorninja** [comment]
I patially fixed thsi. @JeDa try again now.
