### ISSUE TITLE
merge with ughboard?

### ISSUE THREAD

**Issue by Super-toad65** [BBXD/BBXD#14]
hello, since i made a new blargboard fork and now I feel a bit ugh for something. I want to propose you a merge with my stuff, since I improved stuff like SFS connection for spammers and generally proxies.

thanks,

ST65

**Comment by maorninja** [comment]
Sure. Can you send me your new features?

**Comment by Super-toad65** [comment]
okay

**Comment by maorninja** [comment]
Looks legit. Merging.
